using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.Data.Sqlite;
using XmlIndexer.Models;

namespace XmlIndexer.Reports;

/// <summary>
/// Generates standalone Markdown and JSON reports from ecosystem data.
/// </summary>
public class MarkdownJsonExporter
{
    public static string GetHealthIcon(string health) => health switch
    {
        "Healthy" => "✅",
        "Review" => "⚠️",
        "Broken" => "❌",
        _ => "❓"
    };

    public static void GenerateMarkdownReport(string path, ReportData data)
    {
        var md = $@"# 🎮 7D2D Mod Ecosystem Report

Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}

## 📊 Base Game Statistics

| Metric | Value |
|--------|-------|
| Total Definitions | {data.TotalDefinitions:N0} |
| Total Properties | {data.TotalProperties:N0} |
| Cross-References | {data.TotalReferences:N0} |

### Definitions by Type

| Type | Count |
|------|-------|
{string.Join("\n", data.DefinitionsByType.Select(kv => $"| {kv.Key} | {kv.Value:N0} |"))}

## 🔧 Mod Statistics

| Metric | Value |
|--------|-------|
| Total Mods | {data.TotalMods} |
| XML-Only Mods | {data.XmlMods} |
| C#-Only Mods | {data.CSharpMods} |
| Hybrid Mods | {data.HybridMods} |

### XML Operations by Type

| Operation | Count |
|-----------|-------|
{string.Join("\n", data.OperationsByType.Select(kv => $"| {kv.Key} | {kv.Value} |"))}

{(data.CSharpByType.Any() ? $@"### C# Dependencies by Type

| Type | Count |
|------|-------|
{string.Join("\n", data.CSharpByType.Select(kv => $"| {kv.Key} | {kv.Value} |"))}" : "")}

{(data.HarmonyPatches.Any() ? $@"### 🔌 Harmony Patches

| Mod | Target Class | Method | Patch Type |
|-----|--------------|--------|------------|
{string.Join("\n", data.HarmonyPatches.Select(p => $"| {p.ModName} | `{p.ClassName}` | `{p.MethodName}` | {p.PatchType} |"))}" : "")}

{(data.ClassExtensions.Any() ? $@"### 🧬 Class Extensions

| Mod | Extends/Implements | Class |
|-----|-------------------|-------|
{string.Join("\n", data.ClassExtensions.Select(e => $"| {e.ModName} | {e.BaseClass} | `{e.ChildClass}` |"))}" : "")}

## 🌍 Ecosystem Health

| Metric | Value |
|--------|-------|
| Active Entities | {data.ActiveEntities:N0} |
| Modified by Mods | {data.ModifiedEntities} |
| Removed by Mods | {data.RemovedEntities} |
| C# Dependencies | {data.DependedEntities} |

{(data.DangerZone.Any() ? $@"
### ⚠️ Critical Conflicts

| Entity | Removed By | Needed By |
|--------|------------|-----------|
{string.Join("\n", data.DangerZone.Select(d => $"| {d.Type}/{d.Name} | {d.RemovedBy} | {d.DependedBy} |"))}" : @"
### ✅ No Critical Conflicts Detected

All C# mod dependencies are satisfied.")}

## 📦 Mod Overview

**Type Legend:** XML = Config changes only | C# Code = Uses Harmony patches | Hybrid = Both | Assets = Textures/sounds only

**Health Legend:** ✅ Healthy = Safe to use | ⚠️ Review = Check notes | ❌ Broken = Has problems

| Mod Name | Type | Health | Notes |
|----------|------|--------|-------|
{string.Join("\n", data.ModSummary.Select(m => $"| {m.Name} | {m.ModType} | {GetHealthIcon(m.Health)} {m.Health} | {m.HealthNote} |"))}

{GenerateModBehaviorMd(data.ModBehaviors)}

## 🎮 Fun Facts

- **Longest Item Name:** `{data.LongestItemName}`
- **Most Referenced:** `{data.MostReferencedItem}` ({data.MostReferencedCount:N0} things reference it)
- **Most Complex:** `{data.MostComplexEntity}` ({data.MostComplexProps:N0} properties)
- **Most Connected:** `{data.MostConnectedEntity}` (references {data.MostConnectedRefs:N0} different things)
- **Most Depended Upon:** `{data.MostDependedEntity}` ({data.MostDependedCount:N0} entities need this)

{GenerateContestedEntitiesMd(data.ContestedEntities)}

---
*Generated by 7D2D Mod Ecosystem Analyzer*
";

        File.WriteAllText(path, md);
    }

    private static string GenerateContestedEntitiesMd(List<ContestedEntity> entities)
    {
        if (!entities.Any())
            return "✅ **No Shared Entities** - No game entities are modified by multiple mods!";
        
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("## ⚡ Shared Entities\n");
        sb.AppendLine("Entities touched by multiple mods:\n");
        
        foreach (var c in entities)
        {
            sb.AppendLine($"### {c.EntityType}/{c.EntityName}");
            sb.AppendLine($"**Risk:** {c.RiskLevel} - {c.RiskReason}\n");
            sb.AppendLine("| Mod | Operation |");
            sb.AppendLine("|-----|-----------|");
            foreach (var a in c.ModActions)
            {
                sb.AppendLine($"| {a.ModName} | {a.Operation} |");
            }
            sb.AppendLine();
        }
        
        return sb.ToString();
    }

    private static string GenerateModBehaviorMd(List<ModBehavior> behaviors)
    {
        var meaningfulBehaviors = behaviors.Where(b => 
            b.KeyFeatures.Count > 0 || b.Warnings.Count > 0 || !b.OneLiner.Contains("no detectable")).ToList();
        
        if (!meaningfulBehaviors.Any())
            return "## 📝 Behavioral Analysis\n\nNo complex mod behaviors detected.\n";
        
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("## 📝 What Each Mod Does\n");
        sb.AppendLine("Human-readable analysis of what each mod actually does to your game.\n");
        
        foreach (var b in meaningfulBehaviors.OrderByDescending(x => x.KeyFeatures.Count + x.Warnings.Count))
        {
            sb.AppendLine($"### {b.ModName}");
            sb.AppendLine($"*{b.OneLiner}*\n");
            
            if (b.KeyFeatures.Count > 0)
            {
                sb.AppendLine("**What it does:**");
                foreach (var feature in b.KeyFeatures.Take(5))
                    sb.AppendLine($"- {feature}");
                if (b.KeyFeatures.Count > 5)
                    sb.AppendLine($"- ...and {b.KeyFeatures.Count - 5} more");
                sb.AppendLine();
            }
            
            if (b.SystemsAffected.Count > 0)
                sb.AppendLine($"**Systems affected:** {string.Join(", ", b.SystemsAffected)}\n");
            
            if (b.Warnings.Count > 0)
            {
                sb.AppendLine("**Warnings:**");
                foreach (var warning in b.Warnings)
                    sb.AppendLine($"- {warning}");
                sb.AppendLine();
            }
        }
        
        return sb.ToString();
    }

    public static void GenerateJsonExport(string path, ReportData data)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine($@"  ""generated"": ""{DateTime.Now:O}"",");
        sb.AppendLine($@"  ""baseGame"": {{");
        sb.AppendLine($@"    ""totalDefinitions"": {data.TotalDefinitions},");
        sb.AppendLine($@"    ""totalProperties"": {data.TotalProperties},");
        sb.AppendLine($@"    ""totalReferences"": {data.TotalReferences},");
        sb.AppendLine($@"    ""definitionsByType"": {{");
        sb.AppendLine(string.Join(",\n", data.DefinitionsByType.Select(kv => $@"      ""{kv.Key}"": {kv.Value}")));
        sb.AppendLine("    }");
        sb.AppendLine("  },");
        sb.AppendLine($@"  ""mods"": {{");
        sb.AppendLine($@"    ""total"": {data.TotalMods},");
        sb.AppendLine($@"    ""xmlOnly"": {data.XmlMods},");
        sb.AppendLine($@"    ""csharpOnly"": {data.CSharpMods},");
        sb.AppendLine($@"    ""hybrid"": {data.HybridMods},");
        sb.AppendLine($@"    ""operationsByType"": {{");
        sb.AppendLine(string.Join(",\n", data.OperationsByType.Select(kv => $@"      ""{kv.Key}"": {kv.Value}")));
        sb.AppendLine("    },");
        sb.AppendLine($@"    ""list"": [");
        sb.AppendLine(string.Join(",\n", data.ModSummary.Select(m => 
            $@"      {{ ""name"": ""{EscapeJson(m.Name)}"", ""type"": ""{m.ModType}"", ""health"": ""{m.Health}"", ""notes"": ""{EscapeJson(m.HealthNote)}"" }}")));
        sb.AppendLine("    ]");
        sb.AppendLine("  },");
        sb.AppendLine($@"  ""ecosystem"": {{");
        sb.AppendLine($@"    ""activeEntities"": {data.ActiveEntities},");
        sb.AppendLine($@"    ""modifiedEntities"": {data.ModifiedEntities},");
        sb.AppendLine($@"    ""removedEntities"": {data.RemovedEntities},");
        sb.AppendLine($@"    ""dependedEntities"": {data.DependedEntities},");
        sb.AppendLine($@"    ""criticalConflicts"": [");
        sb.AppendLine(string.Join(",\n", data.DangerZone.Select(d => 
            $@"      {{ ""type"": ""{d.Type}"", ""name"": ""{EscapeJson(d.Name)}"", ""removedBy"": ""{EscapeJson(d.RemovedBy)}"", ""neededBy"": ""{EscapeJson(d.DependedBy)}"" }}")));
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        File.WriteAllText(path, sb.ToString());
    }

    private static string EscapeJson(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\n", "\\n")
        .Replace("\r", "\\r")
        .Replace("\t", "\\t");
}
