using System.Text;
using System.Web;

namespace XmlIndexer.Utils;

/// <summary>
/// Builds clickable HTML elements using data attributes instead of inline onclick.
/// This approach eliminates JavaScript string escaping complexity entirely.
/// 
/// Usage:
/// 1. Generate HTML elements with Anchor() or Span()
/// 2. Include GenerateEventHandler() once per page in the script section
/// 3. Define your JavaScript functions normally (they receive string arguments)
/// </summary>
public static class JsClickBuilder
{
    /// <summary>
    /// Build a clickable anchor element with data attributes.
    /// </summary>
    /// <param name="action">The JavaScript function name to call on click</param>
    /// <param name="args">Arguments to pass (stored in data-arg0, data-arg1, etc.)</param>
    /// <param name="innerHtml">Content inside the element (caller must escape if needed)</param>
    /// <param name="style">Optional inline style</param>
    /// <param name="title">Optional title/tooltip</param>
    /// <param name="cssClass">Additional CSS classes (js-click is always added)</param>
    /// <returns>Complete HTML anchor element string</returns>
    public static string Anchor(
        string action,
        string[] args,
        string innerHtml,
        string? style = null,
        string? title = null,
        string? cssClass = null)
    {
        var sb = new StringBuilder();
        sb.Append("<a href=\"#\"");
        sb.Append($" class=\"js-click{(string.IsNullOrEmpty(cssClass) ? "" : " " + cssClass)}\"");
        sb.Append($" data-action=\"{HtmlEncode(action)}\"");

        for (int i = 0; i < args.Length; i++)
        {
            sb.Append($" data-arg{i}=\"{HtmlEncode(args[i] ?? "")}\"");
        }

        if (!string.IsNullOrEmpty(style))
            sb.Append($" style=\"{style}\"");  // Style not encoded - caller provides valid CSS

        if (!string.IsNullOrEmpty(title))
            sb.Append($" title=\"{HtmlEncode(title)}\"");

        sb.Append('>');
        sb.Append(innerHtml);  // Caller responsible for escaping inner content
        sb.Append("</a>");

        return sb.ToString();
    }

    /// <summary>
    /// Build a clickable span element with data attributes.
    /// Use when anchor semantics are not appropriate.
    /// </summary>
    public static string Span(
        string action,
        string[] args,
        string innerHtml,
        string? style = null,
        string? cssClass = null)
    {
        var sb = new StringBuilder();
        sb.Append("<span");
        sb.Append($" class=\"js-click{(string.IsNullOrEmpty(cssClass) ? "" : " " + cssClass)}\"");
        sb.Append($" data-action=\"{HtmlEncode(action)}\"");

        for (int i = 0; i < args.Length; i++)
        {
            sb.Append($" data-arg{i}=\"{HtmlEncode(args[i] ?? "")}\"");
        }

        if (!string.IsNullOrEmpty(style))
            sb.Append($" style=\"{style}\"");

        sb.Append('>');
        sb.Append(innerHtml);
        sb.Append("</span>");

        return sb.ToString();
    }

    /// <summary>
    /// Generate the event delegation JavaScript to include in pages.
    /// Call this ONCE per page that uses js-click elements.
    /// Include in a script tag after your function definitions.
    /// </summary>
    /// <returns>JavaScript code for event delegation</returns>
    public static string GenerateEventHandler()
    {
        return @"
// Event delegation for js-click elements (auto-generated by JsClickBuilder)
// Handles all clicks on elements with class 'js-click'
document.addEventListener('click', function(e) {
    const el = e.target.closest('.js-click');
    if (!el) return;
    
    e.preventDefault();
    const action = el.dataset.action;
    
    // Collect all arguments from data-arg0, data-arg1, etc.
    const args = [];
    let i = 0;
    while (el.dataset['arg' + i] !== undefined) {
        args.push(el.dataset['arg' + i]);
        i++;
    }
    
    // Call the function if it exists
    if (typeof window[action] === 'function') {
        window[action].apply(null, args);
    } else {
        console.error('JsClickBuilder: Unknown action:', action, 'with args:', args);
    }
});
";
    }

    /// <summary>
    /// HTML-encode a string for safe use in attributes.
    /// Handles quotes, ampersands, and angle brackets.
    /// </summary>
    public static string HtmlEncode(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;
        return HttpUtility.HtmlEncode(value);
    }

    /// <summary>
    /// Convenience method for generating a simple one-argument click.
    /// </summary>
    public static string SimpleAnchor(string action, string arg, string text, string? style = null)
    {
        return Anchor(action, new[] { arg }, HtmlEncode(text), style);
    }

    /// <summary>
    /// Convenience method for generating a two-argument click (common pattern).
    /// </summary>
    public static string TwoArgAnchor(string action, string arg0, string arg1, string text, string? style = null)
    {
        return Anchor(action, new[] { arg0, arg1 }, HtmlEncode(text), style);
    }
}
